server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/personal_blog?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSL=false
    username: root
    password: gzh123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.guozh.personal_blog_backend.entity