server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/blog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: a123456.
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      max-lifetime: 1800000 # 30 分钟
      idle-timeout: 600000 # 10 分钟
      connection-timeout: 30000 # 30 秒
      connection-test-query: SELECT 1
      validation-timeout: 3000 # 3 秒
      leak-detection-threshold: 2000 # 2 秒

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.guozh.personal_blog_backend.entity